name: Check Lighthouse score

on:
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate Lighthouse scores
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GH_TOKEN }}
          urls: "https://recoiltodo.netlify.app"
      - name: Verify scores
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: "https://recoiltodo.netlify.app"
          budgetPath: ".github/configs/budget.json"
          configPath: ".github/configs/lighthouserc.json"
