name: Check Lighthouse score

on:
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Audit Netlify deploy preview
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: "recoiltodo.netlify.app"
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: "./report"
